// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hebexkgkyuhpdufolqgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlYmV4a2dreXVocGR1Zm9scWd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MDkyMDksImV4cCI6MjA2NzM4NTIwOX0.BOdiD6N9L0HPPklMTyNlTuRiSaVTL8D9wRb27ijBLXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});